version: '3.8'

services:
  line-provider:
    build:
      context: ./line_provider
      dockerfile: Dockerfile
    container_name: line-provider
    restart: always
    environment:
      - DB_HOST=db_line_provider
      - DB_USER=user_line
      - DB_PASS=12451245
      - DB_NAME=line_provider_db
      - DB_PORT=3306
      - MQ_USER=guest
      - MQ_PWD=guest
      - MQ_HOST=rabbitmq
    depends_on:
      - db_line_provider
      - rabbitmq
    networks:
      - app-network


  bet-maker:
    build:
      context: ./bet_maker
      dockerfile: Dockerfile
    container_name: bet-maker
    restart: always
    environment:
      - DB_HOST=db_bet_maker
      - DB_USER=user_bet
      - DB_PASS=12451245
      - DB_NAME=bet_maker_db
      - DB_PORT=3306
      - MQ_USER=guest
      - MQ_PWD=guest
      - MQ_HOST=rabbitmq
      - LP_HOST=line-provider
    depends_on:
      - line-provider
      - db_bet_maker
      - rabbitmq
    networks:
      - app-network


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network


  db_line_provider:
    image: mysql:8
    container_name: db_line_provider
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwdpwd
      MYSQL_DATABASE: line_provider_db
      MYSQL_USER: user_line
      MYSQL_PASSWORD: 12451245
    ports:
      - "3308:3306"
    volumes:
      - db_data_line:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p12451245" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


  db_bet_maker:
    image: mysql:8
    container_name: db_bet_maker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwdpwd
      MYSQL_DATABASE: bet_maker_db
      MYSQL_USER: user_bet
      MYSQL_PASSWORD: 12451245
    ports:
      - "3307:3306"
    volumes:
      - db_data_bet:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p12451245" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  db_data_line:
  db_data_bet:

networks:
  app-network:
    driver: bridge